name: maven_build
author: ctw04336
description: Build the project using Maven

runs:
  using: "composite"
  steps:
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      shell: bash


